#!/usr/bin/env bun
/**
 * Write the Content-Security-Policy header for Caddy from the finished build: every inline script in
 * every HTML page is allowed by hash. Output: <BUILD_META_DIR>/csp.caddy (default build-meta/),
 * imported by docker/Caddyfile. Runs at the end of `bun run build`.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

import { buildCsp, inlineScripts, scriptHash } from '../src/lib/security/csp';

const ROOT = join(import.meta.dir, '..');
const OUT_DIR = resolve(ROOT, process.env['BUILD_OUT_DIR'] ?? 'dist');
const META_DIR = resolve(ROOT, process.env['BUILD_META_DIR'] ?? 'build-meta');

const files = await readdir(OUT_DIR, { recursive: true });
const pages = files.filter((path) => path.endsWith('.html'));
const hashes = new Set<string>();
for (const page of pages) {
  for (const script of inlineScripts(await readFile(join(OUT_DIR, page), 'utf8')))
    hashes.add(scriptHash(script));
}

// The policy allows fonts from 'self' only: a font inlined as a data: URI would be blocked in production.
for (const file of files.filter((path) => path.endsWith('.css') || path.endsWith('.html'))) {
  if ((await readFile(join(OUT_DIR, file), 'utf8')).includes('data:font/')) {
    console.error(
      `CSP: ${file} inlines a font as a data: URI, which font-src 'self' blocks (astro.config.ts).`,
    );
    process.exit(1);
  }
}

const policy = buildCsp(hashes);
await mkdir(META_DIR, { recursive: true });
await writeFile(
  join(META_DIR, 'csp.caddy'),
  `# Generated by scripts/generate-csp.ts. Do not edit.\nheader Content-Security-Policy "${policy}"\n`,
);
console.log(
  `CSP: ${hashes.size} inline script hashes from ${pages.length} pages → ${join(META_DIR, 'csp.caddy')}`,
);
